export const thead = {
  0: [
    "Instrument",
    "Quantity",
    "Avg. open",
    "Mark price",
    "Liq. price",
    "Unreal. PnL",
    "TP / SL",
    "Est. total",
    "Margin",
    "Settle Price",
    "Order",
  ],
  1: [
    "Instrument",
    "Type",
    "Side",
    "TP / SL",
    "Filled / Quantity",
    "Price",
    "Trigger",
    "Est. total",
    "Reduce",
    "Hidden",
    "Order time",
  ],
  2: [
    "Instrument",
    "Side",
    "Quantity",
    "Trigger",
    "Price",
    "Notional",
    "Reduce only",
    "Order time",
  ],
  3: [
    "Instrument",
    "Type",
    "Side",
    "Filled / Quantity",
    "Order price",
    "Avg. price",
    "Trigger",
    "Est. total",
    "Fee",
    "Status",
    "Reduce",
    "Hidden",
    "Order time",
  ],
  4: [
    "Instrument",
    "Type",
    "Side",
    "Filled / Quantity",
    "Avg. price",
    "Trigger",
    "Realized PnL",
    "Est. total",
    "Fee",
    "Status",
    "Reduce",
    "Hidden",
    "Order time",
  ],
};
