import { GeneralProvider } from "@/context";
import { Footer } from "@/layouts/footer";
import { Header } from "@/layouts/header";
import ReactQueryProvider from "@/lib/react-query/provider";
import { WalletProvider } from "@/lib/wallet-connector";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { OrderlyProvider } from "./common/OrderlyProvider";
import "./globals.css";

// const OrderlyContainer = dynamic(() => import("./common/OrderlyProvider"), {
//   ssr: false,
// });

const inter = Inter({
  weight: "400",
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "VEENO PERP DEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          <OrderlyProvider>
            <ReactQueryProvider>
              <GeneralProvider>
                <Header />
                {children}
                <Footer />
              </GeneralProvider>
            </ReactQueryProvider>
          </OrderlyProvider>{" "}
        </WalletProvider>
      </body>
    </html>
  );
}
