export const beams = [
  {
    initialX: 10,
    translateX: 10,
    duration: 7,
    repeatDelay: 3,
    delay: 2,
  },
  {
    initialX: 600,
    translateX: 600,
    duration: 3,
    repeatDelay: 3,
    delay: 4,
  },
  {
    initialX: 100,
    translateX: 100,
    duration: 7,
    repeatDelay: 7,
    className: "h-6",
  },
  {
    initialX: 400,
    translateX: 400,
    duration: 5,
    repeatDelay: 14,
    delay: 4,
  },
  {
    initialX: 800,
    translateX: 800,
    duration: 11,
    repeatDelay: 2,
    className: "h-20",
  },
  {
    initialX: 1000,
    translateX: 1000,
    duration: 4,
    repeatDelay: 2,
    className: "h-12",
  },
  {
    initialX: 1200,
    translateX: 1200,
    duration: 6,
    repeatDelay: 4,
    delay: 2,
    className: "h-6",
  },
  {
    initialX: 50,
    translateX: 50,
    duration: 8,
    repeatDelay: 5,
    delay: 1,
    className: "h-8",
  },
  {
    initialX: 300,
    translateX: 300,
    duration: 6,
    repeatDelay: 4,
    delay: 3,
  },
  {
    initialX: 700,
    translateX: 700,
    duration: 9,
    repeatDelay: 6,
    className: "h-10",
  },
  {
    initialX: 900,
    translateX: 900,
    duration: 5,
    repeatDelay: 8,
    delay: 2,
  },
  {
    initialX: 1100,
    translateX: 1100,
    duration: 7,
    repeatDelay: 3,
    className: "h-16",
  },
  {
    initialX: 1300,
    translateX: 1300,
    duration: 4,
    repeatDelay: 5,
    delay: 1,
    className: "h-9",
  },
  {
    initialX: 1500,
    translateX: 1500,
    duration: 10,
    repeatDelay: 2,
    delay: 3,
    className: "h-7",
  },
  {
    initialX: 950,
    translateX: 950,
    duration: 8,
    repeatDelay: 4,
    delay: 2,
    className: "h-14",
  },
  {
    initialX: 1050,
    translateX: 1050,
    duration: 6,
    repeatDelay: 3,
    delay: 1,
    className: "h-8",
  },
  {
    initialX: 1150,
    translateX: 1150,
    duration: 9,
    repeatDelay: 5,
    className: "h-10",
  },
  {
    initialX: 1250,
    translateX: 1250,
    duration: 7,
    repeatDelay: 2,
    delay: 3,
    className: "h-16",
  },
  {
    initialX: 1350,
    translateX: 1350,
    duration: 5,
    repeatDelay: 4,
    className: "h-12",
  },
  {
    initialX: 1450,
    translateX: 1450,
    duration: 10,
    repeatDelay: 3,
    delay: 2,
    className: "h-9",
  },
  {
    initialX: 1550,
    translateX: 1550,
    duration: 8,
    repeatDelay: 6,
    className: "h-11",
  },
  {
    initialX: 1650,
    translateX: 1650,
    duration: 6,
    repeatDelay: 4,
    delay: 1,
    className: "h-7",
  },
  {
    initialX: 1750,
    translateX: 1750,
    duration: 9,
    repeatDelay: 5,
    delay: 3,
    className: "h-13",
  },
  {
    initialX: 1850,
    translateX: 1850,
    duration: 7,
    repeatDelay: 2,
    className: "h-15",
  },
];
