export const overrides = () => ({
  "paneProperties.vertGridProperties.color": "rgba(255, 255, 255, 0.06)",
  "paneProperties.horzGridProperties.color": "rgba(255, 255, 255, 0.06)",
  "symbolWatermarkProperties.transparency": 90,
  "scalesProperties.textColor": "rgba(255,255,255,0.8)",
  "mainSeriesProperties.candleStyle.wickUpColor": "#3ab484",
  "mainSeriesProperties.candleStyle.width": "190px",
  "mainSeriesProperties.candleStyle.wickDownColor": "#ea3943",
  "mainSeriesProperties.candleStyle.upColor": "#3ab484",
  "mainSeriesProperties.candleStyle.downColor": "#ea3943",
  "paneProperties.background": "#1B1D22",
  "paneProperties.backgroundType": "solid",
  "scalesProperties.backgroundColor": "#1B1D22",
  "paneProperties.legendProperties.showStudyArguments": true,
  "paneProperties.legendProperties.showStudyTitles": true,
  "paneProperties.legendProperties.showStudyValues": true,
  "paneProperties.legendProperties.showSeriesTitle": true,
  "paneProperties.legendProperties.showSeriesOHLC": true,
  "paneProperties.legendProperties.showLegend": true,
  "paneProperties.legendProperties.showBarChange": true,
  "paneProperties.legendProperties.showBackground": true,
  "mainSeriesProperties.hollowCandleStyle.drawWick": true,
  "mainSeriesProperties.hollowCandleStyle.drawBorder": true,
  "mainSeriesProperties.candleStyle.drawBorder": true,
  "mainSeriesProperties.haStyle.drawWick": true,
  "mainSeriesProperties.haStyle.drawBorder": true,
  "paneProperties.legendProperties.backgroundTransparency": 10,
  "scalesProperties.fontSize": 12,
  volumePaneSize: "small",
});
